name: Flask Deployment
on:
  push:
    branches: [ master ]
jobs:
  Deploy:
    name: Deploy to Ec2
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy in EC2
      env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
          HOST_NAME : ${{ secrets.HOST_NAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}

   
    
    
